on:
  push:
    branches:
      - master

jobs:
  qa:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: interpreter
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: requirements
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry export -f requirements.txt --output requirements.txt
        pip install -r requirements.txt
    - name: linting
      run: |
        pip install pylint
        pylint --max-line-length=88 --disable=too-few-public-methods,missing-module-docstring,unused-import,missing-class-docstring,missing-function-docstring --notes= vpnmupd/
    - name: testing
      run: |
        pip install pytest
        pytest -v
  # release:
  #   runs-on: "ubuntu-latest"
  #   needs: qa
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: release
  #     run: |
  #       pip install poetry
  #       poetry publish --build --username anatolio --password ${{ secret.PYPI_PASSWORD }}
